### ISSUE TITLE
Clicking on `AutoSuggestion' and a number of other controls forces a scroll to the top of the example page

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular_components_example#53]
with `Chrome 63.0.3239.132`

**Comment by nshahan** [comment]
There is a fix in flight internally. Will try to get the update externally ASAP.

**Comment by kevmoo** [comment]
Thanks!

**Comment by kevmoo** [comment]
Seems fixed now!

**Comment by nshahan** [comment]
It looks like the fix worked in Chrome and the current beta version of Firefox but it still exists in Safari, Edge, and the current version of Firefox. I just added info to the internal tracking bug.
